### ISSUE TITLE
Results on Davis dataset.

### ISSUE THREAD

**Issue by donglao** [Haotianz94/IL_video_inpainting#1]
Thanks to the authors for sharing the code. Do you have any plan on releasing pre-computed results on the Davis dataset so that we can make a direct comparison to your results in a follow-up paper? Many thanks!

**Comment by Haotianz94** [comment]
Thanks for your interest in our work. I am sorry that due to the potential implementation differences in data pre-processing (resize, crop) and post-processing (composition), we do not have plan on releasing our results for comparison. Please re-run our code to generate results under the same setting with your results to make comparison.
