### ISSUE TITLE
How to get the inpainted video?

### ISSUE THREAD

**Issue by GOptimistic** [Haotianz94/IL_video_inpainting#9]
After training, I got 20 folders which are corresponding to the 20 passed while training. And I found the images in each folder, but how can I get the inpainted video? I tried to use the images in folder "result\DIP_Vid_Flow\bmx-trees\020\final\full" to make videos. But the effect was bad. So I need your help.

**Comment by Haotianz94** [comment]
Inside "result\DIP_Vid_Flow\bmx-trees\020\final", subfolder named "full" contains fully generated frames, subfolder named "stitch" contains frames that are combining ground-truth background and generated hole region. In the paper, we used results from "full" folder since the results are generally more consistent across hole boundaries.

**Comment by GOptimistic** [comment]
Thanks very much.
